const watches = [
{name:'Lucardo',type:'Automatic · Green',sku:'GCEM216061',tag:'Механика вашего характера.',text:'Глубокий зелёный и открытая архитектура циферблата. Lucardo превращает движение механизма в часть образа — для тех, кто замечает красоту не только снаружи.',specs:[['Механизм','Автоматический'],['Корпус','44 мм'],['Ремешок','Силикон']],url:'automatic-watch-lucardo-green',image:'lucardo.jpg'},
{name:'Dervio',type:'Chronograph · Salmon',sku:'GCEM207212',tag:'Тёплый оттенок уверенности.',text:'Лососевый циферблат и коричневый кожаный ремешок — сочетание, которое хочется рассматривать. Добавьте Dervio к жакету или светлой рубашке, чтобы привычный образ зазвучал по-новому.',specs:[['Функция','Хронограф'],['Корпус','Сталь'],['Ремешок','Кожа']],url:'chronograph-dervio-salmon',image:'dervio.jpg'},
{name:'Petroio',type:'Chronograph · Rose Gold',sku:'GCEM174200',tag:'Когда деталь становится акцентом.',text:'Контраст светлого и чёрного, оттенок розового золота и ремешок с тиснением под крокодила. Крупный Petroio придаёт образу выразительность — от вечерней встречи до особенного события.',specs:[['Функция','Хронограф'],['Корпус','51 мм'],['Ремешок','Кожа']],url:'chronograph-petroio-rose-gold',image:'petroio.jpg'},
{name:'Positano',type:'Chronograph · Black',sku:'GCEM217358',tag:'Ваш ритм. Без лишних слов.',text:'Чёрный циферблат, стальной корпус и силиконовый ремешок. Спортивный характер Positano легко вписывается в городской гардероб: носите его с футболкой, курткой или расслабленным костюмом.',specs:[['Функция','Хронограф'],['Корпус','45 мм'],['Ремешок','Силикон']],url:'chronograph-positano-black-1',image:'positano.jpg'},
{name:'Pesaro',type:'Date · Blue',sku:'GCEM057558',tag:'Синий — ваш новый классический.',text:'Насыщенный синий циферблат и блеск стального браслета. Pesaro собирает образ в единое целое: достаточно надеть часы, поправить манжету — и вы готовы к новому дню.',specs:[['Индикация','Дата'],['Корпус','43 мм'],['Браслет','Сталь']],url:'date-watch-pesaro-blue',image:'pesaro.jpg'}
];
document.querySelector('#hero-art').insertAdjacentHTML('afterbegin','<img src="hero.jpg" alt="Cerruti 1881 Lucardo: зелёные часы со скелетонизированным циферблатом" fetchpriority="high" width="620" height="620"><div class="hero-caption">В ФОКУСЕ КОЛЛЕКЦИИ<strong>Lucardo Automatic</strong></div>');
document.querySelector('#products').innerHTML=watches.map((w,i)=>`<article class="product"><div class="product-art"><span class="index">0${i+1} / 05</span><img src="${w.image}" alt="Наручные часы Cerruti 1881 ${w.name} ${w.type}" loading="lazy" width="500" height="500"><span class="art-label">CERRUTI 1881</span></div><div class="product-text"><div class="eyebrow">${w.type}</div><h3>${w.name}</h3><p class="tagline">${w.tag}</p><p class="description">${w.text}</p><div class="specs">${w.specs.map(s=>`<div><span>${s[0]}</span><strong>${s[1]}</strong></div>`).join('')}</div><a class="shop-link" href="https://www.cerruti.com/products/${w.url}" target="_blank" rel="noopener noreferrer" aria-label="Купить Cerruti ${w.name} на сайте Cerruti">Выбрать ${w.name} <span aria-hidden="true">↗</span></a><span class="reference">${w.sku} · Цена и покупка на сайте Cerruti</span></div></article>`).join('');

